# PORT (MANDATORY FOR RAILWAY)
server.port=${PORT:8080}

# USE H2 DATABASE (FASTEST FIX)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create
spring.h2.console.enabled=true

# OPTIONAL (prevents errors)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
